title: "writeups.sh"
description: "HTB and Academy writeups for people who actually get stuck"
baseurl: "/writeups-site"
url: "https://shasuau.github.io"

# Build
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 6
paginate_path: "/page/:num/"

# Collections
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "writeup"

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
